### ISSUE TITLE
Unable to run with binder

### ISSUE THREAD

**Issue by brillonc** [maahn/pyOptimalEstimation_examples#2]
I am unable to run the examples using binder, without making any changes. Is it normal??

Thank you,

-Charles

**Comment by maahn** [comment]
No, what error do you get?

**Comment by planetaryjain** [comment]
I am also having the same issue and getting the attached error. 

Sonal
<img width="1493" alt="Screenshot 2024-10-08 at 9 36 57 PM" src="https://github.com/user-attachments/assets/fdb2b68a-c20d-4345-a1ae-dc10a2cce12c">

**Comment by maahn** [comment]
Sorry that it took a while, it is now fixed.
